# Generated by Django 6.0.6 on 2026-06-18 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("available_quantity", models.PositiveIntegerField(default=0)),
                ("reserved_quantity", models.PositiveIntegerField(default=0)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "inventories",
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("RESERVE", "Reserve"),
                            ("RELEASE", "Release"),
                            ("SALE", "Sale"),
                            ("RETURN", "Return"),
                            ("DAMAGE", "Damage"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity_delta", models.IntegerField()),
                ("note", models.TextField(blank=True)),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.inventory",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_transactions",
                "indexes": [
                    models.Index(
                        fields=["transaction_type"],
                        name="inventory_t_transac_a372b6_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="inventory_t_created_f087fb_idx"
                    ),
                ],
            },
        ),
    ]
